<?php

namespace Cours4Dev\CourBundle\Repository;

/**
 * CourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourRepository extends \Doctrine\ORM\EntityRepository
{
}
