cours4_dev_formation_homepage:
    path:     /
    defaults: { _controller: Cours4DevFormationBundle:Formation:index }

cours4_dev_formation_add:
    path:     /add
    defaults: { _controller: Cours4DevFormationBundle:Formation:add}

cours4_dev_formation_update:
    path:     /update/{formation}
    defaults: { _controller: Cours4DevFormationBundle:Formation:update}

cours4_dev_formation_delete:
    path:     /delete/{formation}
    defaults: { _controller: Cours4DevFormationBundle:Formation:delete}

