cours4_dev_chapitre:
    resource: "@Cours4DevChapitreBundle/Resources/config/routing.yml"
    prefix:   /chapitre

cours4_dev_formation:
    resource: "@Cours4DevFormationBundle/Resources/config/routing.yml"
    prefix:   /formation

cours4_dev_category:
    resource: "@Cours4DevCategoryBundle/Resources/config/routing.yml"
    prefix:   /category

cours4_devprofessor:
    resource: "@Cours4DevprofessorBundle/Resources/config/routing.yml"
    prefix:   /professor

app:
    resource: '@AppBundle/Controller/'
    type: annotation
